name: Blog CI/CD
on:
  push:
    branches:
      - main
      - master
env:
  TZ: Asia/Shanghai
jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - name: Install hexo dependencies && Generate files
        run: yarn install && yarn run build
      - name: Install coscmd
        run: sudo pip install coscmd
      - name: Configure coscmd
        env:
          SECRET_ID: ${{ secrets.SecretId }}
          SECRET_KEY: ${{ secrets.SecretKey }}
          BUCKET: blog-1253193167
          REGION: ap-shanghai
        run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
      - name: Upload
        run: cd ./public && coscmd upload -r ./ /